# CodeBook for `means.txt`

This codebook describes the structure of the file means.txt:

## Data

The data is made of the processed recordings of 30 subjects performing activities of daily living while carrying a waist-mounted smartphone with embedded inertial sensors. The presented data is limited to the mean/standard deviations components from a larger dataset of available measurements (see the [full dataset](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip), in particular see `features_info.txt` for an in-depth description of the signals measured and the meaning of the features that we list below).

## Origins

The data was extracted from the 
[UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).

## Processing

The original data was processed as follows:

1. The features of type *standard deviation* `*std()` and *mean* `*mean()` were selected for each measurements.
2. The data was partitionned into `Subject->Activity->Feature->[Measurements]`
3. Each vector `[Measurements]` was then replaced by its mean.
Hence, multiples measurements were turned into one number `Subject->Activity->Feature->value`.

(See `README.Rmd` for more details on the processing.)

## Dimensions

The file contains 180 rows (+1 header) and 68 columns.

## Structure

The data is partitioned by Subject Index (`1-30`) / Activity (e.g., `WALKING`) / Feature value (e.g., `-0.5448711`)

The first line of `means.txt` is composed of the 68 headers:

1. Subject Index
2. Activity Name 
3. Features Name (66 columns)

Then, the following 180 rows have type:

1. integer
2. character
3. numeric (66 columns)

## Exact Columns List

1. `Subject`
2. `Activity`
3. `tBodyAcc.mean.X`
4. `tBodyAcc.mean.Y`
5. `tBodyAcc.mean.Z`
6. `tBodyAcc.std.X`
7. `tBodyAcc.std.Y`
8. `tBodyAcc.std.Z`
9. `tGravityAcc.mean.X`
10. `tGravityAcc.mean.Y`
11. `tGravityAcc.mean.Z`
12. `tGravityAcc.std.X`
13. `tGravityAcc.std.Y`
14. `tGravityAcc.std.Z`
15. `tBodyAccJerk.mean.X`
16. `tBodyAccJerk.mean.Y`
17. `tBodyAccJerk.mean.Z`
18. `tBodyAccJerk.std.X`
19. `tBodyAccJerk.std.Y`
20. `tBodyAccJerk.std.Z`
21. `tBodyGyro.mean.X`
22. `tBodyGyro.mean.Y`
23. `tBodyGyro.mean.Z`
24. `tBodyGyro.std.X`
25. `tBodyGyro.std.Y`
26. `tBodyGyro.std.Z`
27. `tBodyGyroJerk.mean.X`
28. `tBodyGyroJerk.mean.Y`
29. `tBodyGyroJerk.mean.Z`
30. `tBodyGyroJerk.std.X`
31. `tBodyGyroJerk.std.Y`
32. `tBodyGyroJerk.std.Z`
33. `tBodyAccMag.mean`
34. `tBodyAccMag.std`
35. `tGravityAccMag.mean`
36. `tGravityAccMag.std`
37. `tBodyAccJerkMag.mean`
38. `tBodyAccJerkMag.std`
39. `tBodyGyroMag.mean`
40. `tBodyGyroMag.std`
41. `tBodyGyroJerkMag.mean`
42. `tBodyGyroJerkMag.std`
43. `fBodyAcc.mean.X`
44. `fBodyAcc.mean.Y`
45. `fBodyAcc.mean.Z`
46. `fBodyAcc.std.X`
47. `fBodyAcc.std.Y`
48. `fBodyAcc.std.Z`
49. `fBodyAccJerk.mean.X`
50. `fBodyAccJerk.mean.Y`
51. `fBodyAccJerk.mean.Z`
52. `fBodyAccJerk.std.X`
53. `fBodyAccJerk.std.Y`
54. `fBodyAccJerk.std.Z`
55. `fBodyGyro.mean.X`
56. `fBodyGyro.mean.Y`
57. `fBodyGyro.mean.Z`
58. `fBodyGyro.std.X`
59. `fBodyGyro.std.Y`
60. `fBodyGyro.std.Z`
61. `fBodyAccMag.mean`
62. `fBodyAccMag.std`
63. `fBodyBodyAccJerkMag.mean`
64. `fBodyBodyAccJerkMag.std`
65. `fBodyBodyGyroMag.mean`
66. `fBodyBodyGyroMag.std`
67. `fBodyBodyGyroJerkMag.mean`
68. `fBodyBodyGyroJerkMag.std`
